library(plotly)
plot_ly(historical_eq, x = ~Longitude, y = ~Latitude, z = ~Depth, size = ~Magnitude,
  marker = list( color = ~Magnitude, symbol = 'circle', sizemode = 'diameter', colorscale = c('#FFE1A1', '#683531'), showscale = TRUE), sizes = c(1, 30),
  text = ~paste('Time:', Time, '<br>Magnitude:', Magnitude, '<br>Latitude:', Latitude,
              '<br>Longitude:', Longitude, '<br>Depth:',Depth, '<br>Province:', Province, 
              '<br>City:', City)) %>%
  layout(title = 'Earthquakes',
         scene = list(xaxis = list(title = 'Longitude',
                                   gridcolor = 'rgb(255, 255, 255)',
                                   zerolinewidth = 1,
                                   ticklen = 5,
                                   gridwidth = 2),
                      yaxis = list(title = 'Latitude',
                                   gridcolor = 'rgb(255, 255, 255)',
                                   zerolinewidth = 1,
                                   ticklen = 5,
                                   gridwith = 2),
                      zaxis = list(title = 'Depth',
                                   gridcolor = 'rgb(255, 255, 255)',
                                   zerolinewidth = 1,
                                   ticklen = 5,
                                   gridwith = 2)),
         paper_bgcolor = 'rgb(243, 243, 243)',
         plot_bgcolor = 'rgb(243, 243, 243)')
